# These tests are the specification. Do not edit this file: fix inventory.py.
import unittest

from inventory import Inventory


class InventoryTest(unittest.TestCase):
    def test_remove_refuses_and_leaves_stock(self):
        inv = Inventory()
        inv.add("bolt", 3)
        with self.assertRaises(ValueError):
            inv.remove("bolt", 5)
        self.assertEqual(inv.stock["bolt"], 3)

    def test_remove(self):
        inv = Inventory()
        inv.add("nut", 10)
        inv.remove("nut", 4)
        self.assertEqual(inv.stock["nut"], 6)

    def test_low_includes_the_threshold(self):
        inv = Inventory()
        inv.add("a", 2)
        inv.add("b", 5)
        inv.add("c", 9)
        self.assertEqual(inv.low(5), ["a", "b"])


if __name__ == "__main__":
    unittest.main()
